version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: veterinary_app

    working_dir: /var/www
    command: tail -f /dev/null

    volumes:
      - ./:/var/www

    ports:
      - "8000:8000"

    depends_on:
      - db

    networks:
      - veterinary_network

  db:
    image: postgres:16

    container_name: veterinary_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: veterinary_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - veterinary_network

networks:
  veterinary_network:

volumes:
  postgres_data: